---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:

    - JOBS=1
    - secure: TC+ChxRmNRWkN1+FHPIC5Atn2xAI94xc7Wx3ccRGbCZ8pjwK9Nx4kKfFgJchwIf3IgB3qQW/GQRznFaGWloruZyzdBn99H3f8mTMLQvX6o9E3cQOPdOsH6SzFGrmeDCaLlBbwNt7SI12VDzQnkTrxPEN4eL4HGGMPEd54sF9oMr+CSkiNLWrg0bGeB2UqtvgESQGwwH7c9K0oHQQFjNTH300hnAH4E/ij9DPhCvbCZ3eWzgau9xeu1IuGLeflElN4cmKeYjcL7GL2BL+U0bxNDsXFOsO7/7RvpKHvKWY8WXmG22tAyk1J98fS37IxooFTNoylDqAK/KZxdCfb8V7s5HDFtNsm1cHBTqvWsK99+UP2qZWE+sILWlMyiRihM501DJ1pw5LM5j+bdVRhIV+Pn8Qp4OFQmjXsKx0sff+4f+q1pvb8uJOscfwLrghSzsfXPDgefp7SyLlIqWnJmNhD8EP+lOeCz5KpZ2mB0ueCUgrGst9dVpQXk4dADVyyAS6cqnwjdCU4k52V8yjNXsuuzaA1fTk2DytJS0hIgGbyCfX8u8BZIFuRk+crZxzrYTYO/tfH+jd547VqMfsmo9EOxq15D+4S59cIAejMiJnvX9YLPG8eh8Q0xgP0r170YYwtqeg44eNJszEwLQEyBMXNTCIV692b4E0IofeZ9zv570=

  matrix:
    - EMBER_TRY_SCENARIO=node-tests

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
  - npm run lint:js
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
  - npm run test:mut
